---
name: Apply - Terraform via ARC
on:
  push:
    branches:
      - main

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

jobs:
  deploy:
    runs-on: arc-dind
    container: image-registry.openshift-image-registry.svc:5000/arc-runners/terraform-runner:latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Git as root
        run: git config --global --add safe.directory '*'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Terraform apply
        run: make apply
